---
build_dev: false
kube_dev: false
headless: no
dockerfile_dest: '../..'
dockerfile_name: 'Dockerfile'
template_dest: '_build'

receptor_image: docker.io/ashish1981/receptor:latest

# Helper vars to construct the proper download URL for the current architecture
image_architecture: '{{ { "x86_64": "amd64", "aarch64": "arm64", "armv7": "arm", "arm64": "arm64", "ppc64le": "ppc64le", "s390x": "s390x" }[ansible_facts.architecture] }}'
